version: '3.3'
services:
    postgres:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=gusty
            - POSTGRES_PASSWORD=demo
            - POSTGRES_DB=airflow
        ports:
            - "5678:5432"
    airflow: &airflow_build
        build:
            context: .
        environment: &airflow_env
          - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
          - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
          - AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER=True
          - AIRFLOW__CORE__LAZY_LOAD_PLUGINS=False
          - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
          - AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE=True
          - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://gusty:demo@postgres:5432/airflow
          - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
          - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_WEBSERVER__SECRET_KEY}
          - AIRFLOW_USER=${AIRFLOW_USER}
          - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
          - EXTRACTOR_GITHUB_TOKEN=${EXTRACTOR_GITHUB_TOKEN}
          - CONNECT_API_KEY=${CONNECT_API_KEY}
          - CONNECT_SERVER=${CONNECT_SERVER}
          - PIPELINE_BUCKET=/usr/local/bucket
          - PIPELINE_WAREHOUSE_URI=/usr/local/bucket/_warehouse
        command: >
            /bin/bash -c "
                cd /usr/local/airflow
                # Wait for PG
                sleep 5

                # Clean up pid
                rm -f airflow-webserver.pid

                # Set up metadata database
                airflow db upgrade

                # Create default user
                airflow users create \
                  --username $AIRFLOW_USER \
                  --password $AIRFLOW_PASSWORD \
                  --email gusty@gusty.com \
                  --firstname Gusty \
                  --lastname User \
                  --role Admin

                # Start airflow
                airflow scheduler &
            	  airflow webserver

                # Keep the server on no matter what
                sleep infinity
            "
        restart: always
        depends_on:
            - postgres
        volumes:
            - ${PWD}/airflow:/usr/local/airflow
            - ${PWD}/bucket:/usr/local/bucket
        ports:
            - "8080:8080"
        networks:
          - default
          - my-proxy-net
    jupyterlab:
        <<: *airflow_build
        ports:
            - "8090:8090"
        command: >
          /bin/bash -c "
              python -m pip install -e airflow
              jupyter lab --port 8090 --LabApp.token=''
          "
        environment:
          - PIPELINE_BUCKET=/home/jovyan/bucket
          - PIPELINE_WAREHOUSE_URI=/home/jovyan/bucket/_warehouse
          - JUPYTERLAB_TOKEN=${JUPYTERLAB_TOKEN}
        volumes:
          - ${PWD}/analyses:/home/jovyan/analyses
          - ${PWD}/airflow:/home/jovyan/airflow
          - ${PWD}/bucket:/home/jovyan/bucket

networks:
  default:
    name: tidyverse-dashboard_default
  my-proxy-net:
    external:
      name: rsconnect
