name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main
    paths:
      - 'airflow/dags/**'
      - 'airflow/plugins/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push Airflow code to GCS
        run: |
          make update-dags AIRFLOW_BUCKET=$AIRFLOW_BUCKET
          make update-plugins AIRFLOW_BUCKET=$AIRFLOW_BUCKET
        env:
          AIRFLOW_BUCKET: ${{ secrets.AIRFLOW_BUCKET }}
